version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  moviesAapi:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    image: moviesapi
    container_name: moviesapi_container
    ports:
      - "8080:8080"
volumes:
  local_pgdata:
  pgadmin-data: