apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: postgres-pod
  template:
    metadata:
      labels:
        bb: postgres-pod
    spec:
      containers:
        - name: postgres-kub-container
          image: my-postgres-db
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: moviesdb-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: postgres-pod
  ports:
    - port: 54320
      targetPort: 5432
      nodePort: 30002