spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://local_pgdb:5432/user
    username: user
    password: admin
    driverClassName: org.postgresql.Driver
    hikari:
      pool-name: movie-cpool
  jpa:
    show-sql: false
    database: postgresql
    open-in-view: false
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 2048KB
      max-request-size: 2048KB
dynamicinput:
  csv:
    file:
      location: /usr/src/academy_awards.csv
  protocol: http
  omdbapi:
    endpoint: http://www.omdbapi.com/?apikey=e5c7611
  algorithm:
    key: secret
    claim: roles

api:
  config :
    activeEnvironment : live

