spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-file-size: 2048KB
      max-request-size: 2048KB

dynamicinput:
  csv:
    file:
      location: src/main/resources/academy_awards.csv
  protocol: http
  omdbapi:
    endpoint: http://www.omdbapi.com/?apikey=e5c7611
  algorithm:
    key: secret
    claim: roles

logging:
  level:
    org.springframework: ERROR
    com.backbase.rest.moviesapi: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: application.log

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method
    oauth2RedirectUrl: /swagger-ui/oauth2-redirect.html
    clientId: "vivek"
    clientSecret: "admin"